const baseProps = {
  color: String,
  bg: String,
  w: [Number, String, Array],
  width: [Number, String, Array],
  minW: [Number, String, Array],
  minWidth: [String, Array],
  maxW: [Number, String, Array],
  maxWidth: [String, Array],
  h: [Number, String, Array],
  height: [Number, String, Array],
  minH: [String, Array],
  minHeight: [Number, String, Array],
  maxH: [String, Array],
  maxHeight: [Number, String, Array],
  d: [String, Array],
  display: [String, Array],
  lineClamp: [String, Number, Array],
  truncate: [Boolean, Number],
  pt: [Number, String, Array],
  pr: [Number, String, Array],
  pb: [Number, String, Array],
  pl: [Number, String, Array],
  px: [Number, String, Array],
  py: [Number, String, Array],
  p: [Number, String, Array],
  mt: [Number, String, Array],
  mr: [Number, String, Array],
  ml: [Number, String, Array],
  mb: [Number, String, Array],
  mx: [Number, String, Array],
  my: [Number, String, Array],
  m: [Number, String, Array],
  rounded: [String, Array],
  roundedTop: [String, Array],
  roundedBottom: [String, Array],
  roundedLeft: [String, Array],
  roundedRight: [String, Array],
  roundedTopRight: [String, Array],
  roundedTopLeft: [String, Array],
  roundedBottomRight: [String, Array],
  roundedBottomLeft: [String, Array],
  b: [String, Array],
  br: [String, Array],
  bb: [String, Array],
  bl: [String, Array],
  bt: [String, Array],
  border: [String, Array],
  borderLeft: [String, Array],
  borderRight: [String, Array],
  borderTop: [String, Array],
  borderBottom: [String, Array],
  shadow: [Number, String, Array],
  backgroundColor: String,
  pos: [String, Array],
  flexDir: [String, Array],
  bgImg: [String, Array],
  bgImage: [String, Array],
  bgSize: [String, Array],
  bgPos: [String, Array],
  bgRepeat: [String, Array],
  borderWidth: [String, Array],
  fontWeight: [String, Array],
  fontFamily: [String, Array],
  fontSize: [String, Array],
  textAlign: [String, Array],
  textDecoration: [String, Array],
  overflow: [String, Array],
  overflowX: [String, Array],
  overflowY: [String, Array],
  textTransform: [String, Array],
  animation: [String, Array],
  alignItems: [String, Array],
  alignContent: [String, Array],
  justifyContent: [String, Array],
  flexWrap: [String, Array],
  flexBasis: [String, Array],
  flexDirection: [String, Array],
  flex: [String, Array],
  justifySelf: [String, Array],
  alignSelf: [String, Array],
  order: [String, Array],
  outline: [String, Array],
  cursor: [String, Array],
  transition: [String, Array],
  borderBottomColor: [String, Array],
  borderTopColor: [String, Array],
  borderLeftColor: [String, Array],
  borderRightColor: [String, Array],
  borderColor: [String, Array],
  borderStyle: [String, Array],
  whiteSpace: [String, Array],
  verticalAlign: [String, Array],
  lineHeight: [Number, String, Array],
  appearance: [String, Array]
  // transform: [String, Array],
  // transformOrigin: [String, Array],
  // visibility: [String, Array],
  // userSelect: [String, Array],
  // pointerEvents: [String, Array],
  // wordBreak: [String, Array],
  // overflowWrap: [String, Array],
  // textOverflow: [String, Array],
  // boxSizing: [String, Array],
  // resize: [String, Array],
  // listStyleType: [String, Array],
  // listStylePosition: [String, Array],
  // listStyleImage: [String, Array],
  // fill: [String, Array],
  // stroke: [String, Array],
  // objectFit: [String, Array],
  // objectPosition: [String, Array],
  // backgroundAttachment: [String, Array],
  // float: [String, Array],
  // willChange: [String, Array]
}

export default baseProps
