const aliases = {
  roundedTop: ['borderTopLeftRadius', 'borderTopRightRadius'],
  roundedBottom: ['borderBottomLeftRadius', 'borderBottomRightRadius'],
  roundedLeft: ['borderTopLeftRadius', 'borderBottomLeftRadius'],
  roundedRight: ['borderTopRightRadius', 'borderBottomRightRadius'],
  roundedTopRight: 'borderTopRightRadius',
  roundedTopLeft: 'borderTopLeftRadius',
  roundedBottomRight: 'borderBottomRightRadius',
  roundedBottomLeft: 'borderBottomLeftRadius',
  rounded: 'borderRadius',
  d: 'display',
  w: 'width',
  minW: 'minWidth',
  maxW: 'maxWidth',
  h: 'height',
  minH: 'minHeight',
  maxH: 'maxHeight',
  bgImg: 'backgroundImage',
  bgImage: 'backgroundImage',
  bgSize: 'backgroundSize',
  bgPos: 'backgroundPosition',
  bgRepeat: 'backgroundRepeat',
  pos: 'position',
  flexDir: 'flexDirection',
  shadow: 'boxShadow',
  b: 'border',
  bl: 'border-left',
  bt: 'border-top',
  br: 'border-right',
  bb: 'border-bottom',
  bgAttachment: 'backgroundAttachment',
  textDecor: 'textDecoration',
  listStylePos: 'listStylePosition',
  listStyleImg: 'listStyleImage'
}

export default aliases
