declare module '@chakra-ui/vue' {
  import Vue from 'vue'

  export class CAccordion extends Vue {}
  export class CAccordionHeader extends Vue {}
  export class CAccordionIcon extends Vue {}
  export class CAccordionItem extends Vue {}
  export class CAccordionPanel extends Vue {}
  export class CAlert extends Vue {}
  export class CAlertDescription extends Vue {}
  export class CAlertDialog extends Vue {}
  export class CAlertDialogBody extends Vue {}
  export class CAlertDialogCloseButton extends Vue {}
  export class CAlertDialogContent extends Vue {}
  export class CAlertDialogFooter extends Vue {}
  export class CAlertDialogHeader extends Vue {}
  export class CAlertDialogOverlay extends Vue {}
  export class CAlertIcon extends Vue {}
  export class CAlertTitle extends Vue {}
  export class CAnimateHeight extends Vue {}
  export class CAspectRatioBox extends Vue {}
  export class CAvatar extends Vue {}
  export class CAvatarBadge extends Vue {}
  export class CAvatarGroup extends Vue {}
  export class CBadge extends Vue {}
  export class CBox extends Vue {}
  export class CBreadcrumb extends Vue {}
  export class CBreadcrumbItem extends Vue {}
  export class CBreadcrumbLink extends Vue {}
  export class CBreadcrumbSeparator extends Vue {}
  export class CButton extends Vue {}
  export class CButtonGroup extends Vue {}
  export class CCheckbox extends Vue {}
  export class CCheckboxGroup extends Vue {}
  export class CCircularProgress extends Vue {}
  export class CCircularProgressLabel extends Vue {}
  export class CCloseButton extends Vue {}
  export class CCode extends Vue {}
  export class CCollapse extends Vue {}
  export class CColorModeProvider extends Vue {}
  export class CControlBox extends Vue {}
  export class CDarkMode extends Vue {}
  export class CDivider extends Vue {}
  export class CDrawer extends Vue {}
  export class CDrawerBody extends Vue {}
  export class CDrawerCloseButton extends Vue {}
  export class CDrawerContent extends Vue {}
  export class CDrawerFooter extends Vue {}
  export class CDrawerHeader extends Vue {}
  export class CDrawerOverlay extends Vue {}
  export class CEditable extends Vue {}
  export class CEditableInput extends Vue {}
  export class CEditablePreview extends Vue {}
  export class CFade extends Vue {}
  export class CFlex extends Vue {}
  export class CFormControl extends Vue {}
  export class CFormErrorMessage extends Vue {}
  export class CFormHelperText extends Vue {}
  export class CFormLabel extends Vue {}
  export class CFragment extends Vue {}
  export class CGrid extends Vue {}
  export class CHeading extends Vue {}
  export class CIcon extends Vue {}
  export class CIconButton extends Vue {}
  export class CImage extends Vue {}
  export class CInput extends Vue {}
  export class CInputAddon extends Vue {}
  export class CInputElement extends Vue {}
  export class CInputGroup extends Vue {}
  export class CInputLeftAddon extends Vue {}
  export class CInputLeftElement extends Vue {}
  export class CInputRightAddon extends Vue {}
  export class CInputRightElement extends Vue {}
  export class CLightMode extends Vue {}
  export class CLink extends Vue {}
  export class CList extends Vue {}
  export class CListIcon extends Vue {}
  export class CListItem extends Vue {}
  export class CMenu extends Vue {}
  export class CMenuButton extends Vue {}
  export class CMenuDivider extends Vue {}
  export class CMenuGroup extends Vue {}
  export class CMenuItem extends Vue {}
  export class CMenuItemOption extends Vue {}
  export class CMenuList extends Vue {}
  export class CMenuOptionGroup extends Vue {}
  export class CModal extends Vue {}
  export class CModalBody extends Vue {}
  export class CModalCloseButton extends Vue {}
  export class CModalContent extends Vue {}
  export class CModalFooter extends Vue {}
  export class CModalHeader extends Vue {}
  export class CModalOverlay extends Vue {}
  export class CNumberDecrementStepper extends Vue {}
  export class CNumberIncrementStepper extends Vue {}
  export class CNumberInput extends Vue {}
  export class CNumberInputField extends Vue {}
  export class CNumberInputStepper extends Vue {}
  export class CPopover extends Vue {}
  export class CPopoverArrow extends Vue {}
  export class CPopoverBody extends Vue {}
  export class CPopoverCloseButton extends Vue {}
  export class CPopoverContent extends Vue {}
  export class CPopoverFooter extends Vue {}
  export class CPopoverHeader extends Vue {}
  export class CPopoverTrigger extends Vue {}
  export class CPopper extends Vue {}
  export class CPopperArrow extends Vue {}
  export class CPortal extends Vue {}
  export class CProgress extends Vue {}
  export class CProgressLabel extends Vue {}
  export class CPseudoBox extends Vue {}
  export class CRadio extends Vue {}
  export class CRadioButtonGroup extends Vue {}
  export class CRadioGroup extends Vue {}
  export class CReset extends Vue {}
  export class CRevealHeight extends Vue {}
  export class CScale extends Vue {}
  export class CSelect extends Vue {}
  export class CSimpleGrid extends Vue {}
  export class CSlide extends Vue {}
  export class CSlideIn extends Vue {}
  export class CSlider extends Vue {}
  export class CSliderFilledTrack extends Vue {}
  export class CSliderThumb extends Vue {}
  export class CSliderTrack extends Vue {}
  export class CSpinner extends Vue {}
  export class CStack extends Vue {}
  export class CStat extends Vue {}
  export class CStatArrow extends Vue {}
  export class CStatGroup extends Vue {}
  export class CStatHelperText extends Vue {}
  export class CStatLabel extends Vue {}
  export class CStatNumber extends Vue {}
  export class CSwitch extends Vue {}
  export class CTab extends Vue {}
  export class CTabList extends Vue {}
  export class CTabPanel extends Vue {}
  export class CTabPanels extends Vue {}
  export class CTabs extends Vue {}
  export class CTag extends Vue {}
  export class CTagCloseButton extends Vue {}
  export class CTagIcon extends Vue {}
  export class CTagLabel extends Vue {}
  export class CText extends Vue {}
  export class CTextarea extends Vue {}
  export class CThemeProvider extends Vue {}
  export class CTooltip extends Vue {}
  export class CVisuallyHidden extends Vue {}
}
